apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${NAMESPACE}

resources:
- secret.yaml
- ../../../components/inference-gateway/
- gateway-parameters.yaml

images:
- name: quay.io/llm-d/gateway-api-inference-extension
  newName: ${EPP_IMAGE}
  newTag: ${EPP_TAG}

patches:
- path: patch-deployments.yaml
- path: patch-gateways.yaml
